apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rt5tht6l6-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rt5tht6l6-java-springboot-gitops